version: '3'

services:
  filed-anaconda:
    container_name: filed-anaconda
    build: .
    ports:
    - "36541:36541"
    volumes:
      - ./:/workdir
    privileged: true  
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined

